### ISSUE TITLE
Worker pod is crashing

### ISSUE THREAD

**Issue by xak47d** [kodekloudhub/example-voting-app-kubernetes#12]
The worker app keeps crashing with this error:
```
System.NotSupportedException: Authentication method not supported (Received: 10)
   at Npgsql.NpgsqlConnector.ParseServerMessage(ReadBuffer buf, BackendMessageCode code, Int32 len, DataRowLoadingMode dataRowLoadingMode, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.DoReadMessage(DataRowLoadingMode dataRowLoadingMode, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessageWithPrepended(DataRowLoadingMode dataRowLoadingMode)
   at Npgsql.NpgsqlConnector.HandleAuthentication(String username, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout)
   at Npgsql.ConnectorPool.Allocate(NpgsqlConnection conn, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnection.OpenInternal()
   at Worker.Program.OpenDbConnection(String connectionString) in /code/src/Worker/Program.cs:line 78
   at Worker.Program.Main(String[] args) in /code/src/Worker/Program.cs:line 19
```

The image uses the Npgsql postgres client that is unable to authenticate to the database, apparently due to authentication method.

**Comment by Vincent990413** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jhonnyV-V** [comment]
check this issue https://github.com/kodekloudhub/example-voting-app-kubernetes/issues/2

**Comment by Blaze27** [comment]
Upgrade the version to v2. Should work.
`image: kodekloud/examplevotingapp_worker:v2`

**Comment by alihu21** [comment]
You can just downgrade your postgresql image to 12.8 and everything will be fine .

<img width="292" height="105" alt="Image" src="https://github.com/user-attachments/assets/917eddc9-4583-4b66-a6fa-97fee3821602" />

**Comment by Vincent990413** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
